### ISSUE TITLE
Gotcha: Missing decimal point

### ISSUE THREAD

**Issue by dallured** [certik/fortran90.org#19]
Add to floating point gotchas.  This one got me today:

integer, parameter:: dp=kind(0.d0)    ! the usual meaning

360_dp is not a floating point number, it's an integer.

Related question:

On the floating point page, why do you recommend always writing all floating point constants with the _dp suffix?

For example, why is 1.0_dp recommended over 1d0 or 1.d0?  Feel free to refer me to any previous discussion.  Thanks.

--Dave

**Comment by pdebuyl** [comment]
This should go in section "gotchas" no? If yes, I'll submit a PR to reflect that. I was not aware of this, even though by reflex I always write real constants with `d0` in my code and use integers when appropriate :-)

**Comment by certik** [comment]
@pdebuyl, yes, that would be great if you could please submit a PR. It should go into gotchas.
