### ISSUE TITLE
syntax error in Allocatable Arrays section

### ISSUE THREAD

**Issue by jbdv-ife** [certik/fortran90.org#44]
Thanks for maintaining this extremely useful online resource.

One possible issue I have noticed: In the section **Allocatable Arrays**, an allocatable variable `lam` is used to illustrate how allocation can be done in a subroutine. Even though `lam` is treated as a one dimensional array, e.g. the statement `allocate(lam(5))`, the shape of the variable is never defined (i.e. `lam(:)` or using `dimension(:)`).

I am no expert and may be wrong, this may be intended just to show the general principle, but if the idea is to provide *minimum working example* code snippets, then perhaps this should be corrected?

**Comment by certik** [comment]
@jbdv-ife thanks a lot for spotting the mistake. I fixed it in #45, if you could review the PR over there, I would appreciate it.

I am happy you found the website useful. If you have other suggestions for improvement, please let me know.

**Comment by jbdv-ife** [comment]
You're welcome, and thanks for the quick response and fix. I'll ask to close the issue then.

**Comment by certik** [comment]
P.S. the issue would get closed by GitHub automatically once the PR is merged, because I put there the "fixes XXX" line.
